// Code generated by ent, DO NOT EDIT.

package custommodelconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the custommodelconfig type in the database.
	Label = "custom_model_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldPrefixMatch holds the string denoting the prefix_match field in the database.
	FieldPrefixMatch = "prefix_match"
	// FieldCapabilities holds the string denoting the capabilities field in the database.
	FieldCapabilities = "capabilities"
	// FieldVideoAPIType holds the string denoting the video_api_type field in the database.
	FieldVideoAPIType = "video_api_type"
	// FieldTemplateID holds the string denoting the template_id field in the database.
	FieldTemplateID = "template_id"
	// Table holds the table name of the custommodelconfig in the database.
	Table = "custom_model_configs"
)

// Columns holds all SQL columns for custommodelconfig fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldModelName,
	FieldPrefixMatch,
	FieldCapabilities,
	FieldVideoAPIType,
	FieldTemplateID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ModelNameValidator is a validator for the "model_name" field. It is called by the builders before save.
	ModelNameValidator func(string) error
	// DefaultPrefixMatch holds the default value on creation for the "prefix_match" field.
	DefaultPrefixMatch bool
	// DefaultVideoAPIType holds the default value on creation for the "video_api_type" field.
	DefaultVideoAPIType string
)

// OrderOption defines the ordering options for the CustomModelConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByPrefixMatch orders the results by the prefix_match field.
func ByPrefixMatch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrefixMatch, opts...).ToFunc()
}

// ByVideoAPIType orders the results by the video_api_type field.
func ByVideoAPIType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoAPIType, opts...).ToFunc()
}

// ByTemplateID orders the results by the template_id field.
func ByTemplateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateID, opts...).ToFunc()
}
