// Code generated by ent, DO NOT EDIT.

package custommodelconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldModelName, v))
}

// PrefixMatch applies equality check predicate on the "prefix_match" field. It's identical to PrefixMatchEQ.
func PrefixMatch(v bool) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldPrefixMatch, v))
}

// VideoAPIType applies equality check predicate on the "video_api_type" field. It's identical to VideoAPITypeEQ.
func VideoAPIType(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldVideoAPIType, v))
}

// TemplateID applies equality check predicate on the "template_id" field. It's identical to TemplateIDEQ.
func TemplateID(v int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldTemplateID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldContainsFold(FieldModelName, v))
}

// PrefixMatchEQ applies the EQ predicate on the "prefix_match" field.
func PrefixMatchEQ(v bool) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldPrefixMatch, v))
}

// PrefixMatchNEQ applies the NEQ predicate on the "prefix_match" field.
func PrefixMatchNEQ(v bool) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNEQ(FieldPrefixMatch, v))
}

// VideoAPITypeEQ applies the EQ predicate on the "video_api_type" field.
func VideoAPITypeEQ(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldVideoAPIType, v))
}

// VideoAPITypeNEQ applies the NEQ predicate on the "video_api_type" field.
func VideoAPITypeNEQ(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNEQ(FieldVideoAPIType, v))
}

// VideoAPITypeIn applies the In predicate on the "video_api_type" field.
func VideoAPITypeIn(vs ...string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldIn(FieldVideoAPIType, vs...))
}

// VideoAPITypeNotIn applies the NotIn predicate on the "video_api_type" field.
func VideoAPITypeNotIn(vs ...string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNotIn(FieldVideoAPIType, vs...))
}

// VideoAPITypeGT applies the GT predicate on the "video_api_type" field.
func VideoAPITypeGT(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGT(FieldVideoAPIType, v))
}

// VideoAPITypeGTE applies the GTE predicate on the "video_api_type" field.
func VideoAPITypeGTE(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGTE(FieldVideoAPIType, v))
}

// VideoAPITypeLT applies the LT predicate on the "video_api_type" field.
func VideoAPITypeLT(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLT(FieldVideoAPIType, v))
}

// VideoAPITypeLTE applies the LTE predicate on the "video_api_type" field.
func VideoAPITypeLTE(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLTE(FieldVideoAPIType, v))
}

// VideoAPITypeContains applies the Contains predicate on the "video_api_type" field.
func VideoAPITypeContains(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldContains(FieldVideoAPIType, v))
}

// VideoAPITypeHasPrefix applies the HasPrefix predicate on the "video_api_type" field.
func VideoAPITypeHasPrefix(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldHasPrefix(FieldVideoAPIType, v))
}

// VideoAPITypeHasSuffix applies the HasSuffix predicate on the "video_api_type" field.
func VideoAPITypeHasSuffix(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldHasSuffix(FieldVideoAPIType, v))
}

// VideoAPITypeIsNil applies the IsNil predicate on the "video_api_type" field.
func VideoAPITypeIsNil() predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldIsNull(FieldVideoAPIType))
}

// VideoAPITypeNotNil applies the NotNil predicate on the "video_api_type" field.
func VideoAPITypeNotNil() predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNotNull(FieldVideoAPIType))
}

// VideoAPITypeEqualFold applies the EqualFold predicate on the "video_api_type" field.
func VideoAPITypeEqualFold(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEqualFold(FieldVideoAPIType, v))
}

// VideoAPITypeContainsFold applies the ContainsFold predicate on the "video_api_type" field.
func VideoAPITypeContainsFold(v string) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldContainsFold(FieldVideoAPIType, v))
}

// TemplateIDEQ applies the EQ predicate on the "template_id" field.
func TemplateIDEQ(v int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldEQ(FieldTemplateID, v))
}

// TemplateIDNEQ applies the NEQ predicate on the "template_id" field.
func TemplateIDNEQ(v int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNEQ(FieldTemplateID, v))
}

// TemplateIDIn applies the In predicate on the "template_id" field.
func TemplateIDIn(vs ...int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldIn(FieldTemplateID, vs...))
}

// TemplateIDNotIn applies the NotIn predicate on the "template_id" field.
func TemplateIDNotIn(vs ...int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNotIn(FieldTemplateID, vs...))
}

// TemplateIDGT applies the GT predicate on the "template_id" field.
func TemplateIDGT(v int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGT(FieldTemplateID, v))
}

// TemplateIDGTE applies the GTE predicate on the "template_id" field.
func TemplateIDGTE(v int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldGTE(FieldTemplateID, v))
}

// TemplateIDLT applies the LT predicate on the "template_id" field.
func TemplateIDLT(v int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLT(FieldTemplateID, v))
}

// TemplateIDLTE applies the LTE predicate on the "template_id" field.
func TemplateIDLTE(v int64) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldLTE(FieldTemplateID, v))
}

// TemplateIDIsNil applies the IsNil predicate on the "template_id" field.
func TemplateIDIsNil() predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldIsNull(FieldTemplateID))
}

// TemplateIDNotNil applies the NotNil predicate on the "template_id" field.
func TemplateIDNotNil() predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.FieldNotNull(FieldTemplateID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomModelConfig) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomModelConfig) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomModelConfig) predicate.CustomModelConfig {
	return predicate.CustomModelConfig(sql.NotPredicates(p))
}
