package service

import (
	"encoding/json"
	"net/url"
	"sort"
	"strings"
)

const (
	codexWorkspaceMetadataMaxDepth = 5
	codexWorkspaceMetadataMaxBytes = 8192
)

// sanitizeCodexTurnMetadataValue keeps the official workspace projection
// useful for upstream risk evaluation while removing local paths and remote
// credential material. Invalid metadata is left untouched so the existing
// protocol error handling remains authoritative.
func sanitizeCodexTurnMetadataValue(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return raw
	}
	metadata := make(map[string]any)
	if err := json.Unmarshal([]byte(raw), &metadata); err != nil {
		return raw
	}
	value, changed, keep := sanitizedCodexTurnMetadataMap(metadata)
	if !changed {
		return raw
	}
	if !keep {
		return `{"redacted":true}`
	}
	encoded, err := json.Marshal(value)
	if err != nil || len(encoded) > codexWorkspaceMetadataMaxBytes {
		return `{"redacted":true}`
	}
	return string(encoded)
}

func sanitizedCodexTurnMetadataMap(metadata map[string]any) (map[string]any, bool, bool) {
	value, changed, keep := sanitizeCodexWorkspaceValue(metadata, "", 0, false)
	if !keep {
		return nil, true, false
	}
	sanitized, ok := value.(map[string]any)
	if !ok {
		return metadata, changed, true
	}
	return sanitized, changed, true
}

func sanitizeCodexTurnMetadataMapInPlace(metadata map[string]any) {
	if metadata == nil {
		return
	}
	sanitized, changed, keep := sanitizedCodexTurnMetadataMap(metadata)
	if !changed {
		return
	}
	for key := range metadata {
		delete(metadata, key)
	}
	if !keep {
		metadata["redacted"] = true
		return
	}
	for key, value := range sanitized {
		metadata[key] = value
	}
}

// normalizeUntrustedCodexTurnMetadataValue is the boundary policy for a raw
// x-codex-turn-metadata request header when no Codex fingerprint plan is active.
// The app-server owns identity, sandbox, and approval provenance; a gateway
// client must not be able to inject those values into an OAuth principal.
// Semantic routing fields such as thread_source and turn_trigger remain
// available as bounded observations, but they are never treated as grants.
func normalizeUntrustedCodexTurnMetadataValue(raw string, ids *codexOutboundSessionIDs) (string, bool) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", false
	}

	metadata := make(map[string]any)
	if err := json.Unmarshal([]byte(raw), &metadata); err != nil || metadata == nil {
		return "", false
	}
	sanitizeCodexTurnMetadataMapInPlace(metadata)

	// These fields are core-owned in the current Codex app-server. They are
	// either regenerated by a fingerprint plan or deliberately omitted on the
	// ordinary OAuth path; preserving a client-supplied value would make the
	// header an identity/permission injection channel.
	for _, key := range []string{
		"installation_id",
		"turn_id",
		"window_id",
		"window_number",
		"context_window_id",
		"root_turn_id",
		"forked_from_thread_id",
		"forked_from_ordinal_exclusive",
		"parent_thread_id",
		"parent_turn_id",
		"parent_response_id",
		"guardian_credits_requested",
		"sandbox",
		"sandbox_mode",
		"auto_review_enabled",
		"node_repl_auto_review_required",
		"node_repl_disabled",
		"x-codex-installation-id",
		"x-codex-window-id",
		"x-codex-turn-metadata",
		"x-codex-parent-thread-id",
		"x-openai-subagent",
		"x-codex-ws-stream-request-start-ms",
		"code_mode_tool_names",
	} {
		delete(metadata, key)
	}

	// Only the structured session projection produced by this gateway may
	// reintroduce identity values. This keeps raw header and body projections
	// account-scoped even when the request is retried on another OAuth account.
	if ids != nil {
		if ids.installationID != "" {
			metadata["installation_id"] = ids.installationID
		}
		if ids.sessionID != "" {
			metadata["session_id"] = ids.sessionID
		}
		if ids.threadID != "" {
			metadata["thread_id"] = ids.threadID
		}
		if ids.parentThreadID != "" {
			metadata["parent_thread_id"] = ids.parentThreadID
		}
		if ids.subagent != "" && validCodexSubagentValue(ids.subagent) {
			metadata["subagent_kind"] = ids.subagent
		}
	}

	for _, key := range []string{"request_kind", "thread_source", "turn_trigger", "subagent_kind"} {
		value, exists := metadata[key]
		if !exists {
			continue
		}
		text, ok := value.(string)
		text = strings.TrimSpace(text)
		if !ok || text == "" || len(text) > codexExtraMetadataMaxValueBytes {
			delete(metadata, key)
			continue
		}
		metadata[key] = text
	}
	if subagent, ok := metadata["subagent_kind"].(string); ok && !validCodexSubagentValue(subagent) {
		delete(metadata, "subagent_kind")
	}

	// Apply the same bounded extra-key policy as the full Codex projection. This
	// prevents an arbitrary header map from becoming an unbounded risk signal or
	// a cross-principal fingerprint.
	projectCodexFullSimulationTurnMetadata(metadata)
	encoded, err := json.Marshal(metadata)
	if err != nil || len(encoded) > codexWorkspaceMetadataMaxBytes {
		return "", false
	}
	return string(encoded), true
}

// sanitizeOpenAICodexClientMetadataMap applies the server-owned boundary to the
// outer Responses client_metadata object on every OAuth path, not only full
// simulation. Fingerprinting may later add a stronger synthetic projection;
// this function first removes client-selected identity/approval fields so an
// ordinary OAuth request cannot bypass that projection by choosing a different
// body shape.
func sanitizeOpenAICodexClientMetadataMap(metadata map[string]any, account *Account, ids *codexOutboundSessionIDs) bool {
	if metadata == nil {
		return false
	}
	changed := false

	if raw, exists := metadata["x-codex-turn-metadata"]; exists {
		text, ok := raw.(string)
		if !ok {
			delete(metadata, "x-codex-turn-metadata")
			changed = true
		} else if normalized, valid := normalizeUntrustedCodexTurnMetadataValue(text, ids); !valid {
			delete(metadata, "x-codex-turn-metadata")
			changed = true
		} else if normalized != text {
			metadata["x-codex-turn-metadata"] = normalized
			changed = true
		}
	}

	// Installation identity is owned by the selected OAuth account. Prefer its
	// persisted device value and otherwise use the deterministic per-account
	// virtual-client projection; a client value is never authoritative.
	deviceID := ""
	if account != nil {
		deviceID = strings.TrimSpace(resolveConvergedInstallationID(account))
	}
	if deviceID == "" {
		if _, exists := metadata["x-codex-installation-id"]; exists {
			delete(metadata, "x-codex-installation-id")
			changed = true
		}
	} else if current, ok := metadata["x-codex-installation-id"].(string); !ok || strings.TrimSpace(current) != deviceID {
		metadata["x-codex-installation-id"] = deviceID
		changed = true
	}

	// All other identity, window, approval, and semantic projection fields are
	// removed first. Only the session plan calculated for this OAuth account may
	// reintroduce the compatible subset below.
	for _, key := range []string{
		"installation_id",
		"session_id",
		"thread_id",
		"turn_id",
		"x-codex-window-id",
		"window_number",
		"context_window_id",
		"x-codex-parent-thread-id",
		"x-openai-subagent",
		"parent_turn_id",
		"root_turn_id",
		"parent_response_id",
		"guardian_credits_requested",
		"x-codex-ws-stream-request-start-ms",
	} {
		if _, exists := metadata[key]; !exists {
			continue
		}
		delete(metadata, key)
		changed = true
	}

	if ids != nil {
		if ids.sessionID != "" && metadata["session_id"] != ids.sessionID {
			metadata["session_id"] = ids.sessionID
			changed = true
		}
		if ids.threadID != "" && metadata["thread_id"] != ids.threadID {
			metadata["thread_id"] = ids.threadID
			changed = true
		}
		if ids.parentThreadID != "" && metadata["x-codex-parent-thread-id"] != ids.parentThreadID {
			metadata["x-codex-parent-thread-id"] = ids.parentThreadID
			changed = true
		}
		if ids.subagent != "" && validCodexSubagentValue(ids.subagent) && metadata["x-openai-subagent"] != ids.subagent {
			metadata["x-openai-subagent"] = ids.subagent
			changed = true
		}
	}
	return changed
}

func sanitizeOpenAICodexClientMetadataPayload(payload map[string]any, account *Account, ids *codexOutboundSessionIDs) bool {
	if payload == nil {
		return false
	}
	raw, exists := payload["client_metadata"]
	if !exists || raw == nil {
		return false
	}
	metadata, ok := mutableCodexClientMetadata(raw)
	if !ok {
		delete(payload, "client_metadata")
		return true
	}
	changed := sanitizeOpenAICodexClientMetadataMap(metadata, account, ids)
	if changed {
		payload["client_metadata"] = metadata
	}
	return changed
}

func sanitizeCodexWorkspaceValue(value any, key string, depth int, inWorkspace bool) (any, bool, bool) {
	if depth > codexWorkspaceMetadataMaxDepth {
		return nil, true, false
	}

	switch typed := value.(type) {
	case map[string]any:
		out := make(map[string]any, len(typed))
		changed := false
		for _, childKey := range sortedCodexWorkspaceKeys(typed) {
			child := typed[childKey]
			childInWorkspace := inWorkspace || codexWorkspaceContainerKey(childKey)
			if childInWorkspace && codexWorkspaceSensitiveKey(childKey) {
				changed = true
				continue
			}
			sanitized, childChanged, keep := sanitizeCodexWorkspaceValue(child, childKey, depth+1, childInWorkspace)
			if childChanged {
				changed = true
			}
			if keep {
				out[childKey] = sanitized
			} else {
				changed = true
			}
		}
		return out, changed, true
	case []any:
		out := make([]any, 0, len(typed))
		changed := false
		for _, child := range typed {
			sanitized, childChanged, keep := sanitizeCodexWorkspaceValue(child, key, depth+1, inWorkspace)
			changed = changed || childChanged
			if keep {
				out = append(out, sanitized)
			} else {
				changed = true
			}
		}
		return out, changed, true
	case string:
		if (inWorkspace && codexWorkspacePathKey(key)) || codexRootWorkspacePathKey(key) {
			if strings.TrimSpace(typed) == "" {
				return typed, false, true
			}
			return stableCodexWorkspacePath(typed), true, true
		}
		if inWorkspace && codexWorkspaceRemoteKey(key) {
			sanitized, changed := sanitizeCodexRemoteURL(typed)
			return sanitized, changed, true
		}
		return typed, false, true
	default:
		return value, false, true
	}
}

func codexWorkspaceContainerKey(key string) bool {
	switch strings.ToLower(strings.TrimSpace(key)) {
	case "workspace", "workspaces", "workspace_info", "workspace_metadata":
		return true
	default:
		return false
	}
}

func sortedCodexWorkspaceKeys(values map[string]any) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func codexWorkspaceSensitiveKey(key string) bool {
	lower := strings.ToLower(strings.TrimSpace(key))
	for _, marker := range []string{"token", "secret", "password", "credential", "authorization", "cookie"} {
		if strings.Contains(lower, marker) {
			return true
		}
	}
	return false
}

func codexWorkspacePathKey(key string) bool {
	switch strings.ToLower(strings.TrimSpace(key)) {
	case "path", "cwd", "workspace_path", "absolute_path", "worktree", "git_dir", "root", "root_path":
		return true
	default:
		return false
	}
}

func codexRootWorkspacePathKey(key string) bool {
	switch strings.ToLower(strings.TrimSpace(key)) {
	case "cwd", "workspace_path", "absolute_path", "worktree", "root_path":
		return true
	default:
		return false
	}
}

func codexWorkspaceRemoteKey(key string) bool {
	lower := strings.ToLower(strings.TrimSpace(key))
	return strings.Contains(lower, "remote") || strings.Contains(lower, "url") || lower == "origin"
}

func stableCodexWorkspacePath(_ string) string {
	return "workspace:redacted"
}

func sanitizeCodexRemoteURL(raw string) (string, bool) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return raw, false
	}
	parsed, err := url.Parse(raw)
	if err == nil && parsed.Scheme != "" && parsed.Host != "" {
		changed := parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != ""
		parsed.User = nil
		parsed.RawQuery = ""
		parsed.Fragment = ""
		return parsed.String(), changed
	}
	// Git's scp-like form has no URL parser userinfo field. Remove the user
	// portion while retaining the host and repository path for coarse matching.
	if at := strings.IndexByte(raw, '@'); at > 0 {
		if colon := strings.IndexByte(raw[at+1:], ':'); colon >= 0 {
			return raw[at+1:], true
		}
	}
	return raw, false
}
