// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/custommodelconfig"
)

// CustomModelConfigCreate is the builder for creating a CustomModelConfig entity.
type CustomModelConfigCreate struct {
	config
	mutation *CustomModelConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomModelConfigCreate) SetCreatedAt(v time.Time) *CustomModelConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomModelConfigCreate) SetNillableCreatedAt(v *time.Time) *CustomModelConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CustomModelConfigCreate) SetUpdatedAt(v time.Time) *CustomModelConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CustomModelConfigCreate) SetNillableUpdatedAt(v *time.Time) *CustomModelConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetModelName sets the "model_name" field.
func (_c *CustomModelConfigCreate) SetModelName(v string) *CustomModelConfigCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetPrefixMatch sets the "prefix_match" field.
func (_c *CustomModelConfigCreate) SetPrefixMatch(v bool) *CustomModelConfigCreate {
	_c.mutation.SetPrefixMatch(v)
	return _c
}

// SetNillablePrefixMatch sets the "prefix_match" field if the given value is not nil.
func (_c *CustomModelConfigCreate) SetNillablePrefixMatch(v *bool) *CustomModelConfigCreate {
	if v != nil {
		_c.SetPrefixMatch(*v)
	}
	return _c
}

// SetCapabilities sets the "capabilities" field.
func (_c *CustomModelConfigCreate) SetCapabilities(v []string) *CustomModelConfigCreate {
	_c.mutation.SetCapabilities(v)
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *CustomModelConfigCreate) SetTemplateID(v int64) *CustomModelConfigCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_c *CustomModelConfigCreate) SetNillableTemplateID(v *int64) *CustomModelConfigCreate {
	if v != nil {
		_c.SetTemplateID(*v)
	}
	return _c
}

// Mutation returns the CustomModelConfigMutation object of the builder.
func (_c *CustomModelConfigCreate) Mutation() *CustomModelConfigMutation {
	return _c.mutation
}

// Save creates the CustomModelConfig in the database.
func (_c *CustomModelConfigCreate) Save(ctx context.Context) (*CustomModelConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomModelConfigCreate) SaveX(ctx context.Context) *CustomModelConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomModelConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomModelConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomModelConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := custommodelconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := custommodelconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.PrefixMatch(); !ok {
		v := custommodelconfig.DefaultPrefixMatch
		_c.mutation.SetPrefixMatch(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomModelConfigCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CustomModelConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CustomModelConfig.updated_at"`)}
	}
	if _, ok := _c.mutation.ModelName(); !ok {
		return &ValidationError{Name: "model_name", err: errors.New(`ent: missing required field "CustomModelConfig.model_name"`)}
	}
	if v, ok := _c.mutation.ModelName(); ok {
		if err := custommodelconfig.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "CustomModelConfig.model_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PrefixMatch(); !ok {
		return &ValidationError{Name: "prefix_match", err: errors.New(`ent: missing required field "CustomModelConfig.prefix_match"`)}
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		return &ValidationError{Name: "capabilities", err: errors.New(`ent: missing required field "CustomModelConfig.capabilities"`)}
	}
	return nil
}

func (_c *CustomModelConfigCreate) sqlSave(ctx context.Context) (*CustomModelConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomModelConfigCreate) createSpec() (*CustomModelConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomModelConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(custommodelconfig.Table, sqlgraph.NewFieldSpec(custommodelconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(custommodelconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(custommodelconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(custommodelconfig.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.PrefixMatch(); ok {
		_spec.SetField(custommodelconfig.FieldPrefixMatch, field.TypeBool, value)
		_node.PrefixMatch = value
	}
	if value, ok := _c.mutation.Capabilities(); ok {
		_spec.SetField(custommodelconfig.FieldCapabilities, field.TypeJSON, value)
		_node.Capabilities = value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(custommodelconfig.FieldTemplateID, field.TypeInt64, value)
		_node.TemplateID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomModelConfig.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomModelConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomModelConfigCreate) OnConflict(opts ...sql.ConflictOption) *CustomModelConfigUpsertOne {
	_c.conflict = opts
	return &CustomModelConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomModelConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomModelConfigCreate) OnConflictColumns(columns ...string) *CustomModelConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomModelConfigUpsertOne{
		create: _c,
	}
}

type (
	// CustomModelConfigUpsertOne is the builder for "upsert"-ing
	//  one CustomModelConfig node.
	CustomModelConfigUpsertOne struct {
		create *CustomModelConfigCreate
	}

	// CustomModelConfigUpsert is the "OnConflict" setter.
	CustomModelConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomModelConfigUpsert) SetUpdatedAt(v time.Time) *CustomModelConfigUpsert {
	u.Set(custommodelconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomModelConfigUpsert) UpdateUpdatedAt() *CustomModelConfigUpsert {
	u.SetExcluded(custommodelconfig.FieldUpdatedAt)
	return u
}

// SetModelName sets the "model_name" field.
func (u *CustomModelConfigUpsert) SetModelName(v string) *CustomModelConfigUpsert {
	u.Set(custommodelconfig.FieldModelName, v)
	return u
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *CustomModelConfigUpsert) UpdateModelName() *CustomModelConfigUpsert {
	u.SetExcluded(custommodelconfig.FieldModelName)
	return u
}

// SetPrefixMatch sets the "prefix_match" field.
func (u *CustomModelConfigUpsert) SetPrefixMatch(v bool) *CustomModelConfigUpsert {
	u.Set(custommodelconfig.FieldPrefixMatch, v)
	return u
}

// UpdatePrefixMatch sets the "prefix_match" field to the value that was provided on create.
func (u *CustomModelConfigUpsert) UpdatePrefixMatch() *CustomModelConfigUpsert {
	u.SetExcluded(custommodelconfig.FieldPrefixMatch)
	return u
}

// SetCapabilities sets the "capabilities" field.
func (u *CustomModelConfigUpsert) SetCapabilities(v []string) *CustomModelConfigUpsert {
	u.Set(custommodelconfig.FieldCapabilities, v)
	return u
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *CustomModelConfigUpsert) UpdateCapabilities() *CustomModelConfigUpsert {
	u.SetExcluded(custommodelconfig.FieldCapabilities)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *CustomModelConfigUpsert) SetTemplateID(v int64) *CustomModelConfigUpsert {
	u.Set(custommodelconfig.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *CustomModelConfigUpsert) UpdateTemplateID() *CustomModelConfigUpsert {
	u.SetExcluded(custommodelconfig.FieldTemplateID)
	return u
}

// AddTemplateID adds v to the "template_id" field.
func (u *CustomModelConfigUpsert) AddTemplateID(v int64) *CustomModelConfigUpsert {
	u.Add(custommodelconfig.FieldTemplateID, v)
	return u
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *CustomModelConfigUpsert) ClearTemplateID() *CustomModelConfigUpsert {
	u.SetNull(custommodelconfig.FieldTemplateID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CustomModelConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomModelConfigUpsertOne) UpdateNewValues() *CustomModelConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(custommodelconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomModelConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomModelConfigUpsertOne) Ignore() *CustomModelConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomModelConfigUpsertOne) DoNothing() *CustomModelConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomModelConfigCreate.OnConflict
// documentation for more info.
func (u *CustomModelConfigUpsertOne) Update(set func(*CustomModelConfigUpsert)) *CustomModelConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomModelConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomModelConfigUpsertOne) SetUpdatedAt(v time.Time) *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomModelConfigUpsertOne) UpdateUpdatedAt() *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetModelName sets the "model_name" field.
func (u *CustomModelConfigUpsertOne) SetModelName(v string) *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *CustomModelConfigUpsertOne) UpdateModelName() *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.UpdateModelName()
	})
}

// SetPrefixMatch sets the "prefix_match" field.
func (u *CustomModelConfigUpsertOne) SetPrefixMatch(v bool) *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.SetPrefixMatch(v)
	})
}

// UpdatePrefixMatch sets the "prefix_match" field to the value that was provided on create.
func (u *CustomModelConfigUpsertOne) UpdatePrefixMatch() *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.UpdatePrefixMatch()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *CustomModelConfigUpsertOne) SetCapabilities(v []string) *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *CustomModelConfigUpsertOne) UpdateCapabilities() *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.UpdateCapabilities()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *CustomModelConfigUpsertOne) SetTemplateID(v int64) *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.SetTemplateID(v)
	})
}

// AddTemplateID adds v to the "template_id" field.
func (u *CustomModelConfigUpsertOne) AddTemplateID(v int64) *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.AddTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *CustomModelConfigUpsertOne) UpdateTemplateID() *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.UpdateTemplateID()
	})
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *CustomModelConfigUpsertOne) ClearTemplateID() *CustomModelConfigUpsertOne {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.ClearTemplateID()
	})
}

// Exec executes the query.
func (u *CustomModelConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomModelConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomModelConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CustomModelConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CustomModelConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CustomModelConfigCreateBulk is the builder for creating many CustomModelConfig entities in bulk.
type CustomModelConfigCreateBulk struct {
	config
	err      error
	builders []*CustomModelConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the CustomModelConfig entities in the database.
func (_c *CustomModelConfigCreateBulk) Save(ctx context.Context) ([]*CustomModelConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomModelConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomModelConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomModelConfigCreateBulk) SaveX(ctx context.Context) []*CustomModelConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomModelConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomModelConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomModelConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomModelConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomModelConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomModelConfigUpsertBulk {
	_c.conflict = opts
	return &CustomModelConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomModelConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomModelConfigCreateBulk) OnConflictColumns(columns ...string) *CustomModelConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomModelConfigUpsertBulk{
		create: _c,
	}
}

// CustomModelConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of CustomModelConfig nodes.
type CustomModelConfigUpsertBulk struct {
	create *CustomModelConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CustomModelConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomModelConfigUpsertBulk) UpdateNewValues() *CustomModelConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(custommodelconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomModelConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomModelConfigUpsertBulk) Ignore() *CustomModelConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomModelConfigUpsertBulk) DoNothing() *CustomModelConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomModelConfigCreateBulk.OnConflict
// documentation for more info.
func (u *CustomModelConfigUpsertBulk) Update(set func(*CustomModelConfigUpsert)) *CustomModelConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomModelConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomModelConfigUpsertBulk) SetUpdatedAt(v time.Time) *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomModelConfigUpsertBulk) UpdateUpdatedAt() *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetModelName sets the "model_name" field.
func (u *CustomModelConfigUpsertBulk) SetModelName(v string) *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *CustomModelConfigUpsertBulk) UpdateModelName() *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.UpdateModelName()
	})
}

// SetPrefixMatch sets the "prefix_match" field.
func (u *CustomModelConfigUpsertBulk) SetPrefixMatch(v bool) *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.SetPrefixMatch(v)
	})
}

// UpdatePrefixMatch sets the "prefix_match" field to the value that was provided on create.
func (u *CustomModelConfigUpsertBulk) UpdatePrefixMatch() *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.UpdatePrefixMatch()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *CustomModelConfigUpsertBulk) SetCapabilities(v []string) *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *CustomModelConfigUpsertBulk) UpdateCapabilities() *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.UpdateCapabilities()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *CustomModelConfigUpsertBulk) SetTemplateID(v int64) *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.SetTemplateID(v)
	})
}

// AddTemplateID adds v to the "template_id" field.
func (u *CustomModelConfigUpsertBulk) AddTemplateID(v int64) *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.AddTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *CustomModelConfigUpsertBulk) UpdateTemplateID() *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.UpdateTemplateID()
	})
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *CustomModelConfigUpsertBulk) ClearTemplateID() *CustomModelConfigUpsertBulk {
	return u.Update(func(s *CustomModelConfigUpsert) {
		s.ClearTemplateID()
	})
}

// Exec executes the query.
func (u *CustomModelConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomModelConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomModelConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomModelConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
