// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/custommodelrequesttemplate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CustomModelRequestTemplateUpdate is the builder for updating CustomModelRequestTemplate entities.
type CustomModelRequestTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *CustomModelRequestTemplateMutation
}

// Where appends a list predicates to the CustomModelRequestTemplateUpdate builder.
func (_u *CustomModelRequestTemplateUpdate) Where(ps ...predicate.CustomModelRequestTemplate) *CustomModelRequestTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomModelRequestTemplateUpdate) SetUpdatedAt(v time.Time) *CustomModelRequestTemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CustomModelRequestTemplateUpdate) SetName(v string) *CustomModelRequestTemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CustomModelRequestTemplateUpdate) SetNillableName(v *string) *CustomModelRequestTemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CustomModelRequestTemplateUpdate) SetDescription(v string) *CustomModelRequestTemplateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CustomModelRequestTemplateUpdate) SetNillableDescription(v *string) *CustomModelRequestTemplateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CustomModelRequestTemplateUpdate) ClearDescription() *CustomModelRequestTemplateUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetRequestAdapter sets the "request_adapter" field.
func (_u *CustomModelRequestTemplateUpdate) SetRequestAdapter(v map[string]interface{}) *CustomModelRequestTemplateUpdate {
	_u.mutation.SetRequestAdapter(v)
	return _u
}

// Mutation returns the CustomModelRequestTemplateMutation object of the builder.
func (_u *CustomModelRequestTemplateUpdate) Mutation() *CustomModelRequestTemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomModelRequestTemplateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomModelRequestTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomModelRequestTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomModelRequestTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomModelRequestTemplateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := custommodelrequesttemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomModelRequestTemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := custommodelrequesttemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CustomModelRequestTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := custommodelrequesttemplate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "CustomModelRequestTemplate.description": %w`, err)}
		}
	}
	return nil
}

func (_u *CustomModelRequestTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(custommodelrequesttemplate.Table, custommodelrequesttemplate.Columns, sqlgraph.NewFieldSpec(custommodelrequesttemplate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(custommodelrequesttemplate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.RequestAdapter(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldRequestAdapter, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{custommodelrequesttemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomModelRequestTemplateUpdateOne is the builder for updating a single CustomModelRequestTemplate entity.
type CustomModelRequestTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomModelRequestTemplateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomModelRequestTemplateUpdateOne) SetUpdatedAt(v time.Time) *CustomModelRequestTemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CustomModelRequestTemplateUpdateOne) SetName(v string) *CustomModelRequestTemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CustomModelRequestTemplateUpdateOne) SetNillableName(v *string) *CustomModelRequestTemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CustomModelRequestTemplateUpdateOne) SetDescription(v string) *CustomModelRequestTemplateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CustomModelRequestTemplateUpdateOne) SetNillableDescription(v *string) *CustomModelRequestTemplateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CustomModelRequestTemplateUpdateOne) ClearDescription() *CustomModelRequestTemplateUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetRequestAdapter sets the "request_adapter" field.
func (_u *CustomModelRequestTemplateUpdateOne) SetRequestAdapter(v map[string]interface{}) *CustomModelRequestTemplateUpdateOne {
	_u.mutation.SetRequestAdapter(v)
	return _u
}

// Mutation returns the CustomModelRequestTemplateMutation object of the builder.
func (_u *CustomModelRequestTemplateUpdateOne) Mutation() *CustomModelRequestTemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the CustomModelRequestTemplateUpdate builder.
func (_u *CustomModelRequestTemplateUpdateOne) Where(ps ...predicate.CustomModelRequestTemplate) *CustomModelRequestTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomModelRequestTemplateUpdateOne) Select(field string, fields ...string) *CustomModelRequestTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomModelRequestTemplate entity.
func (_u *CustomModelRequestTemplateUpdateOne) Save(ctx context.Context) (*CustomModelRequestTemplate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomModelRequestTemplateUpdateOne) SaveX(ctx context.Context) *CustomModelRequestTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomModelRequestTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomModelRequestTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomModelRequestTemplateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := custommodelrequesttemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomModelRequestTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := custommodelrequesttemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CustomModelRequestTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := custommodelrequesttemplate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "CustomModelRequestTemplate.description": %w`, err)}
		}
	}
	return nil
}

func (_u *CustomModelRequestTemplateUpdateOne) sqlSave(ctx context.Context) (_node *CustomModelRequestTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(custommodelrequesttemplate.Table, custommodelrequesttemplate.Columns, sqlgraph.NewFieldSpec(custommodelrequesttemplate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CustomModelRequestTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, custommodelrequesttemplate.FieldID)
		for _, f := range fields {
			if !custommodelrequesttemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != custommodelrequesttemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(custommodelrequesttemplate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.RequestAdapter(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldRequestAdapter, field.TypeJSON, value)
	}
	_node = &CustomModelRequestTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{custommodelrequesttemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
