// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/custommodelconfig"
)

// CustomModelConfig is the model entity for the CustomModelConfig schema.
type CustomModelConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 模型名称
	ModelName string `json:"model_name,omitempty"`
	// 是否按模型名前缀匹配
	PrefixMatch bool `json:"prefix_match,omitempty"`
	// 模型能力列表，如 ["image", "video", "audio"]
	Capabilities []string `json:"capabilities,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CustomModelConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case custommodelconfig.FieldCapabilities:
			values[i] = new([]byte)
		case custommodelconfig.FieldPrefixMatch:
			values[i] = new(sql.NullBool)
		case custommodelconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case custommodelconfig.FieldModelName:
			values[i] = new(sql.NullString)
		case custommodelconfig.FieldCreatedAt, custommodelconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CustomModelConfig fields.
func (_m *CustomModelConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case custommodelconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case custommodelconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case custommodelconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case custommodelconfig.FieldModelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_name", values[i])
			} else if value.Valid {
				_m.ModelName = value.String
			}
		case custommodelconfig.FieldPrefixMatch:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field prefix_match", values[i])
			} else if value.Valid {
				_m.PrefixMatch = value.Bool
			}
		case custommodelconfig.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CustomModelConfig.
// This includes values selected through modifiers, order, etc.
func (_m *CustomModelConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CustomModelConfig.
// Note that you need to call CustomModelConfig.Unwrap() before calling this method if this CustomModelConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CustomModelConfig) Update() *CustomModelConfigUpdateOne {
	return NewCustomModelConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CustomModelConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CustomModelConfig) Unwrap() *CustomModelConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CustomModelConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CustomModelConfig) String() string {
	var builder strings.Builder
	builder.WriteString("CustomModelConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("model_name=")
	builder.WriteString(_m.ModelName)
	builder.WriteString(", ")
	builder.WriteString("prefix_match=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrefixMatch))
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteByte(')')
	return builder.String()
}

// CustomModelConfigs is a parsable slice of CustomModelConfig.
type CustomModelConfigs []*CustomModelConfig
