// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/custommodelconfig"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CustomModelConfigUpdate is the builder for updating CustomModelConfig entities.
type CustomModelConfigUpdate struct {
	config
	hooks    []Hook
	mutation *CustomModelConfigMutation
}

// Where appends a list predicates to the CustomModelConfigUpdate builder.
func (_u *CustomModelConfigUpdate) Where(ps ...predicate.CustomModelConfig) *CustomModelConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomModelConfigUpdate) SetUpdatedAt(v time.Time) *CustomModelConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *CustomModelConfigUpdate) SetModelName(v string) *CustomModelConfigUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *CustomModelConfigUpdate) SetNillableModelName(v *string) *CustomModelConfigUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *CustomModelConfigUpdate) SetCapabilities(v []string) *CustomModelConfigUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *CustomModelConfigUpdate) AppendCapabilities(v []string) *CustomModelConfigUpdate {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// Mutation returns the CustomModelConfigMutation object of the builder.
func (_u *CustomModelConfigUpdate) Mutation() *CustomModelConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomModelConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomModelConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomModelConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomModelConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomModelConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := custommodelconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomModelConfigUpdate) check() error {
	if v, ok := _u.mutation.ModelName(); ok {
		if err := custommodelconfig.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "CustomModelConfig.model_name": %w`, err)}
		}
	}
	return nil
}

func (_u *CustomModelConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(custommodelconfig.Table, custommodelconfig.Columns, sqlgraph.NewFieldSpec(custommodelconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(custommodelconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(custommodelconfig.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(custommodelconfig.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, custommodelconfig.FieldCapabilities, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{custommodelconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomModelConfigUpdateOne is the builder for updating a single CustomModelConfig entity.
type CustomModelConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomModelConfigMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomModelConfigUpdateOne) SetUpdatedAt(v time.Time) *CustomModelConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *CustomModelConfigUpdateOne) SetModelName(v string) *CustomModelConfigUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *CustomModelConfigUpdateOne) SetNillableModelName(v *string) *CustomModelConfigUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *CustomModelConfigUpdateOne) SetCapabilities(v []string) *CustomModelConfigUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *CustomModelConfigUpdateOne) AppendCapabilities(v []string) *CustomModelConfigUpdateOne {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// Mutation returns the CustomModelConfigMutation object of the builder.
func (_u *CustomModelConfigUpdateOne) Mutation() *CustomModelConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the CustomModelConfigUpdate builder.
func (_u *CustomModelConfigUpdateOne) Where(ps ...predicate.CustomModelConfig) *CustomModelConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomModelConfigUpdateOne) Select(field string, fields ...string) *CustomModelConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomModelConfig entity.
func (_u *CustomModelConfigUpdateOne) Save(ctx context.Context) (*CustomModelConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomModelConfigUpdateOne) SaveX(ctx context.Context) *CustomModelConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomModelConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomModelConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomModelConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := custommodelconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomModelConfigUpdateOne) check() error {
	if v, ok := _u.mutation.ModelName(); ok {
		if err := custommodelconfig.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "CustomModelConfig.model_name": %w`, err)}
		}
	}
	return nil
}

func (_u *CustomModelConfigUpdateOne) sqlSave(ctx context.Context) (_node *CustomModelConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(custommodelconfig.Table, custommodelconfig.Columns, sqlgraph.NewFieldSpec(custommodelconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CustomModelConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, custommodelconfig.FieldID)
		for _, f := range fields {
			if !custommodelconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != custommodelconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(custommodelconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(custommodelconfig.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(custommodelconfig.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, custommodelconfig.FieldCapabilities, value)
		})
	}
	_node = &CustomModelConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{custommodelconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
