// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/custommodelrequesttemplate"
)

// CustomModelRequestTemplate is the model entity for the CustomModelRequestTemplate schema.
type CustomModelRequestTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 模板名称
	Name string `json:"name,omitempty"`
	// 模板说明
	Description string `json:"description,omitempty"`
	// 请求适配规则
	RequestAdapter map[string]interface{} `json:"request_adapter,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CustomModelRequestTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case custommodelrequesttemplate.FieldRequestAdapter:
			values[i] = new([]byte)
		case custommodelrequesttemplate.FieldID:
			values[i] = new(sql.NullInt64)
		case custommodelrequesttemplate.FieldName, custommodelrequesttemplate.FieldDescription:
			values[i] = new(sql.NullString)
		case custommodelrequesttemplate.FieldCreatedAt, custommodelrequesttemplate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CustomModelRequestTemplate fields.
func (_m *CustomModelRequestTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case custommodelrequesttemplate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case custommodelrequesttemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case custommodelrequesttemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case custommodelrequesttemplate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case custommodelrequesttemplate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case custommodelrequesttemplate.FieldRequestAdapter:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_adapter", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestAdapter); err != nil {
					return fmt.Errorf("unmarshal field request_adapter: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CustomModelRequestTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *CustomModelRequestTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CustomModelRequestTemplate.
// Note that you need to call CustomModelRequestTemplate.Unwrap() before calling this method if this CustomModelRequestTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CustomModelRequestTemplate) Update() *CustomModelRequestTemplateUpdateOne {
	return NewCustomModelRequestTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CustomModelRequestTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CustomModelRequestTemplate) Unwrap() *CustomModelRequestTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CustomModelRequestTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CustomModelRequestTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("CustomModelRequestTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("request_adapter=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestAdapter))
	builder.WriteByte(')')
	return builder.String()
}

// CustomModelRequestTemplates is a parsable slice of CustomModelRequestTemplate.
type CustomModelRequestTemplates []*CustomModelRequestTemplate
