// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/custommodelrequesttemplate"
)

// CustomModelRequestTemplateCreate is the builder for creating a CustomModelRequestTemplate entity.
type CustomModelRequestTemplateCreate struct {
	config
	mutation *CustomModelRequestTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomModelRequestTemplateCreate) SetCreatedAt(v time.Time) *CustomModelRequestTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomModelRequestTemplateCreate) SetNillableCreatedAt(v *time.Time) *CustomModelRequestTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CustomModelRequestTemplateCreate) SetUpdatedAt(v time.Time) *CustomModelRequestTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CustomModelRequestTemplateCreate) SetNillableUpdatedAt(v *time.Time) *CustomModelRequestTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *CustomModelRequestTemplateCreate) SetName(v string) *CustomModelRequestTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *CustomModelRequestTemplateCreate) SetDescription(v string) *CustomModelRequestTemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CustomModelRequestTemplateCreate) SetNillableDescription(v *string) *CustomModelRequestTemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetRequestAdapter sets the "request_adapter" field.
func (_c *CustomModelRequestTemplateCreate) SetRequestAdapter(v map[string]interface{}) *CustomModelRequestTemplateCreate {
	_c.mutation.SetRequestAdapter(v)
	return _c
}

// Mutation returns the CustomModelRequestTemplateMutation object of the builder.
func (_c *CustomModelRequestTemplateCreate) Mutation() *CustomModelRequestTemplateMutation {
	return _c.mutation
}

// Save creates the CustomModelRequestTemplate in the database.
func (_c *CustomModelRequestTemplateCreate) Save(ctx context.Context) (*CustomModelRequestTemplate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomModelRequestTemplateCreate) SaveX(ctx context.Context) *CustomModelRequestTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomModelRequestTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomModelRequestTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomModelRequestTemplateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := custommodelrequesttemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := custommodelrequesttemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := custommodelrequesttemplate.DefaultDescription
		_c.mutation.SetDescription(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomModelRequestTemplateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CustomModelRequestTemplate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CustomModelRequestTemplate.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CustomModelRequestTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := custommodelrequesttemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CustomModelRequestTemplate.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := custommodelrequesttemplate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "CustomModelRequestTemplate.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestAdapter(); !ok {
		return &ValidationError{Name: "request_adapter", err: errors.New(`ent: missing required field "CustomModelRequestTemplate.request_adapter"`)}
	}
	return nil
}

func (_c *CustomModelRequestTemplateCreate) sqlSave(ctx context.Context) (*CustomModelRequestTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomModelRequestTemplateCreate) createSpec() (*CustomModelRequestTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomModelRequestTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(custommodelrequesttemplate.Table, sqlgraph.NewFieldSpec(custommodelrequesttemplate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.RequestAdapter(); ok {
		_spec.SetField(custommodelrequesttemplate.FieldRequestAdapter, field.TypeJSON, value)
		_node.RequestAdapter = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomModelRequestTemplate.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomModelRequestTemplateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomModelRequestTemplateCreate) OnConflict(opts ...sql.ConflictOption) *CustomModelRequestTemplateUpsertOne {
	_c.conflict = opts
	return &CustomModelRequestTemplateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomModelRequestTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomModelRequestTemplateCreate) OnConflictColumns(columns ...string) *CustomModelRequestTemplateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomModelRequestTemplateUpsertOne{
		create: _c,
	}
}

type (
	// CustomModelRequestTemplateUpsertOne is the builder for "upsert"-ing
	//  one CustomModelRequestTemplate node.
	CustomModelRequestTemplateUpsertOne struct {
		create *CustomModelRequestTemplateCreate
	}

	// CustomModelRequestTemplateUpsert is the "OnConflict" setter.
	CustomModelRequestTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomModelRequestTemplateUpsert) SetUpdatedAt(v time.Time) *CustomModelRequestTemplateUpsert {
	u.Set(custommodelrequesttemplate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsert) UpdateUpdatedAt() *CustomModelRequestTemplateUpsert {
	u.SetExcluded(custommodelrequesttemplate.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *CustomModelRequestTemplateUpsert) SetName(v string) *CustomModelRequestTemplateUpsert {
	u.Set(custommodelrequesttemplate.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsert) UpdateName() *CustomModelRequestTemplateUpsert {
	u.SetExcluded(custommodelrequesttemplate.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *CustomModelRequestTemplateUpsert) SetDescription(v string) *CustomModelRequestTemplateUpsert {
	u.Set(custommodelrequesttemplate.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsert) UpdateDescription() *CustomModelRequestTemplateUpsert {
	u.SetExcluded(custommodelrequesttemplate.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *CustomModelRequestTemplateUpsert) ClearDescription() *CustomModelRequestTemplateUpsert {
	u.SetNull(custommodelrequesttemplate.FieldDescription)
	return u
}

// SetRequestAdapter sets the "request_adapter" field.
func (u *CustomModelRequestTemplateUpsert) SetRequestAdapter(v map[string]interface{}) *CustomModelRequestTemplateUpsert {
	u.Set(custommodelrequesttemplate.FieldRequestAdapter, v)
	return u
}

// UpdateRequestAdapter sets the "request_adapter" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsert) UpdateRequestAdapter() *CustomModelRequestTemplateUpsert {
	u.SetExcluded(custommodelrequesttemplate.FieldRequestAdapter)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CustomModelRequestTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomModelRequestTemplateUpsertOne) UpdateNewValues() *CustomModelRequestTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(custommodelrequesttemplate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomModelRequestTemplate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomModelRequestTemplateUpsertOne) Ignore() *CustomModelRequestTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomModelRequestTemplateUpsertOne) DoNothing() *CustomModelRequestTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomModelRequestTemplateCreate.OnConflict
// documentation for more info.
func (u *CustomModelRequestTemplateUpsertOne) Update(set func(*CustomModelRequestTemplateUpsert)) *CustomModelRequestTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomModelRequestTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomModelRequestTemplateUpsertOne) SetUpdatedAt(v time.Time) *CustomModelRequestTemplateUpsertOne {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsertOne) UpdateUpdatedAt() *CustomModelRequestTemplateUpsertOne {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *CustomModelRequestTemplateUpsertOne) SetName(v string) *CustomModelRequestTemplateUpsertOne {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsertOne) UpdateName() *CustomModelRequestTemplateUpsertOne {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *CustomModelRequestTemplateUpsertOne) SetDescription(v string) *CustomModelRequestTemplateUpsertOne {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsertOne) UpdateDescription() *CustomModelRequestTemplateUpsertOne {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CustomModelRequestTemplateUpsertOne) ClearDescription() *CustomModelRequestTemplateUpsertOne {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.ClearDescription()
	})
}

// SetRequestAdapter sets the "request_adapter" field.
func (u *CustomModelRequestTemplateUpsertOne) SetRequestAdapter(v map[string]interface{}) *CustomModelRequestTemplateUpsertOne {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.SetRequestAdapter(v)
	})
}

// UpdateRequestAdapter sets the "request_adapter" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsertOne) UpdateRequestAdapter() *CustomModelRequestTemplateUpsertOne {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.UpdateRequestAdapter()
	})
}

// Exec executes the query.
func (u *CustomModelRequestTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomModelRequestTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomModelRequestTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CustomModelRequestTemplateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CustomModelRequestTemplateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CustomModelRequestTemplateCreateBulk is the builder for creating many CustomModelRequestTemplate entities in bulk.
type CustomModelRequestTemplateCreateBulk struct {
	config
	err      error
	builders []*CustomModelRequestTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the CustomModelRequestTemplate entities in the database.
func (_c *CustomModelRequestTemplateCreateBulk) Save(ctx context.Context) ([]*CustomModelRequestTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomModelRequestTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomModelRequestTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomModelRequestTemplateCreateBulk) SaveX(ctx context.Context) []*CustomModelRequestTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomModelRequestTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomModelRequestTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomModelRequestTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomModelRequestTemplateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomModelRequestTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomModelRequestTemplateUpsertBulk {
	_c.conflict = opts
	return &CustomModelRequestTemplateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomModelRequestTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomModelRequestTemplateCreateBulk) OnConflictColumns(columns ...string) *CustomModelRequestTemplateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomModelRequestTemplateUpsertBulk{
		create: _c,
	}
}

// CustomModelRequestTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of CustomModelRequestTemplate nodes.
type CustomModelRequestTemplateUpsertBulk struct {
	create *CustomModelRequestTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CustomModelRequestTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomModelRequestTemplateUpsertBulk) UpdateNewValues() *CustomModelRequestTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(custommodelrequesttemplate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomModelRequestTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomModelRequestTemplateUpsertBulk) Ignore() *CustomModelRequestTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomModelRequestTemplateUpsertBulk) DoNothing() *CustomModelRequestTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomModelRequestTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *CustomModelRequestTemplateUpsertBulk) Update(set func(*CustomModelRequestTemplateUpsert)) *CustomModelRequestTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomModelRequestTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomModelRequestTemplateUpsertBulk) SetUpdatedAt(v time.Time) *CustomModelRequestTemplateUpsertBulk {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsertBulk) UpdateUpdatedAt() *CustomModelRequestTemplateUpsertBulk {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *CustomModelRequestTemplateUpsertBulk) SetName(v string) *CustomModelRequestTemplateUpsertBulk {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsertBulk) UpdateName() *CustomModelRequestTemplateUpsertBulk {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *CustomModelRequestTemplateUpsertBulk) SetDescription(v string) *CustomModelRequestTemplateUpsertBulk {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsertBulk) UpdateDescription() *CustomModelRequestTemplateUpsertBulk {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CustomModelRequestTemplateUpsertBulk) ClearDescription() *CustomModelRequestTemplateUpsertBulk {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.ClearDescription()
	})
}

// SetRequestAdapter sets the "request_adapter" field.
func (u *CustomModelRequestTemplateUpsertBulk) SetRequestAdapter(v map[string]interface{}) *CustomModelRequestTemplateUpsertBulk {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.SetRequestAdapter(v)
	})
}

// UpdateRequestAdapter sets the "request_adapter" field to the value that was provided on create.
func (u *CustomModelRequestTemplateUpsertBulk) UpdateRequestAdapter() *CustomModelRequestTemplateUpsertBulk {
	return u.Update(func(s *CustomModelRequestTemplateUpsert) {
		s.UpdateRequestAdapter()
	})
}

// Exec executes the query.
func (u *CustomModelRequestTemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomModelRequestTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomModelRequestTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomModelRequestTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
