// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/custommodelrequesttemplate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CustomModelRequestTemplateDelete is the builder for deleting a CustomModelRequestTemplate entity.
type CustomModelRequestTemplateDelete struct {
	config
	hooks    []Hook
	mutation *CustomModelRequestTemplateMutation
}

// Where appends a list predicates to the CustomModelRequestTemplateDelete builder.
func (_d *CustomModelRequestTemplateDelete) Where(ps ...predicate.CustomModelRequestTemplate) *CustomModelRequestTemplateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CustomModelRequestTemplateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CustomModelRequestTemplateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CustomModelRequestTemplateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(custommodelrequesttemplate.Table, sqlgraph.NewFieldSpec(custommodelrequesttemplate.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CustomModelRequestTemplateDeleteOne is the builder for deleting a single CustomModelRequestTemplate entity.
type CustomModelRequestTemplateDeleteOne struct {
	_d *CustomModelRequestTemplateDelete
}

// Where appends a list predicates to the CustomModelRequestTemplateDelete builder.
func (_d *CustomModelRequestTemplateDeleteOne) Where(ps ...predicate.CustomModelRequestTemplate) *CustomModelRequestTemplateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CustomModelRequestTemplateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{custommodelrequesttemplate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CustomModelRequestTemplateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
