import {
  normalizePlatformQuotasMap,
  type DefaultPlatformQuotasMap,
  type SystemSettings,
} from "@/features/admin-settings/data/dtos/systemSettingsDtos";
import type { NotifyEmailEntry } from "@/types";
import { defaultLoginAgreementDocuments } from "./settingsAgreementResolver";
import { defaultClaudeOAuthSystemPromptBlocks } from "./settingsClaudePromptResolver";

export const tablePageSizeMin = 5;
export const tablePageSizeMax = 1000;
export const tablePageSizeDefault = 20;

export type SettingsForm = Omit<
  SystemSettings,
  | "wechat_connect_open_enabled"
  | "wechat_connect_mp_enabled"
  | "wechat_connect_mobile_enabled"
> & {
  smtp_password: string;
  turnstile_secret_key: string;
  recaptcha_secret_key: string;
  cap_secret_key: string;
  tencent_captcha_app_secret_key: string;
  tencent_captcha_cloud_secret_id: string;
  tencent_captcha_cloud_secret_key: string;
  aliyun_captcha_access_key_secret: string;
  linuxdo_connect_client_secret: string;
  dingtalk_connect_client_secret: string;
  wechat_connect_app_secret: string;
  wechat_connect_open_app_secret: string;
  wechat_connect_mp_app_secret: string;
  wechat_connect_mobile_app_secret: string;
  wechat_connect_open_enabled: boolean;
  wechat_connect_mp_enabled: boolean;
  wechat_connect_mobile_enabled: boolean;
  oidc_connect_client_secret: string;
  github_oauth_client_secret: string;
  google_oauth_client_secret: string;
  force_email_on_third_party_signup: boolean;
  openai_low_upstream_rate_priority_enabled: boolean;
  openai_oauth_scheduling_rate_multiplier: number;
  openai_content_session_burst_balance_enabled: boolean;
  openai_advanced_scheduler_enabled: boolean;
  openai_advanced_scheduler_sticky_weighted_enabled: boolean;
  openai_advanced_scheduler_subscription_priority_enabled: boolean;
  openai_advanced_scheduler_lb_top_k: string;
  openai_advanced_scheduler_weight_priority: string;
  openai_advanced_scheduler_weight_load: string;
  openai_advanced_scheduler_weight_queue: string;
  openai_advanced_scheduler_weight_error_rate: string;
  openai_advanced_scheduler_weight_ttft: string;
  openai_advanced_scheduler_weight_reset: string;
  openai_advanced_scheduler_weight_quota_headroom: string;
  openai_advanced_scheduler_weight_upstream_cost: string;
  openai_advanced_scheduler_weight_previous_response: string;
  openai_advanced_scheduler_weight_session_sticky: string;
  scheduler_v2_enabled: boolean;
  scheduler_v2_status: string;
  scheduler_v2_error: string;
  scheduler_v2_candidate_limit: number;
  scheduler_v2_scan_limit: number;
  request_priority_admission_enabled: boolean;
  request_priority_pending_limit_per_instance: number;
  request_priority_pending_mib_per_instance: number;
  default_platform_quotas: DefaultPlatformQuotasMap;
};

type LocalText = (zh: string, en: string) => string;

export function createSettingsForm(localText: LocalText): SettingsForm {
  return {
    registration_enabled: true,
    email_verify_enabled: false,
    registration_email_suffix_whitelist: [],
    promo_code_enabled: true,
    invitation_code_enabled: false,
    password_reset_enabled: false,
    totp_enabled: false,
    totp_encryption_key_configured: false,
    passkey_enabled: false,
    passkey_configured: false,
    passkey_rp_id: "",
    passkey_rp_origins: [],
    session_binding_enabled: false,
    step_up_enabled: false,
    audit_log_retention_days: 180,
    login_agreement_enabled: false,
    login_agreement_mode: "modal",
    login_agreement_updated_at: "2026-03-31",
    login_agreement_documents: defaultLoginAgreementDocuments(localText),
    default_balance: 0,
    default_platform_quotas:
      normalizePlatformQuotasMap() as DefaultPlatformQuotasMap,
    affiliate_rebate_rate: 20,
    affiliate_rebate_freeze_hours: 0,
    affiliate_rebate_duration_days: 0,
    affiliate_rebate_per_invitee_cap: 0,
    affiliate_admin_recharge_enabled: false,
    default_concurrency: 1,
    default_subscriptions: [],
    force_email_on_third_party_signup: false,
    default_user_rpm_limit: 0,
    site_name: "Sub2API",
    site_logo: "",
    site_subtitle: "Subscription to API Conversion Platform",
    api_base_url: "",
    contact_info: "",
    doc_url: "",
	home_content: "",
	compact_home_enabled: false,
	backend_mode_enabled: false,
    hide_ccs_import_button: false,
    payment_enabled: false,
    risk_control_enabled: false,
    cyber_session_block_enabled: false,
    cyber_session_block_ttl_seconds: 3600,
    payment_min_amount: 1,
    payment_max_amount: 10000,
    payment_daily_limit: 50000,
    payment_max_pending_orders: 3,
    payment_order_timeout_minutes: 30,
    payment_balance_disabled: false,
    payment_balance_recharge_multiplier: 1,
    payment_subscription_usd_to_cny_rate: 0,
    payment_recharge_fee_rate: 0,
    payment_enabled_types: [],
    payment_help_image_url: "",
    payment_help_text: "",
    payment_product_name_prefix: "",
    payment_product_name_suffix: "",
    payment_load_balance_strategy: "round-robin",
    payment_cancel_rate_limit_enabled: false,
    payment_cancel_rate_limit_max: 10,
    payment_cancel_rate_limit_window: 1,
    payment_cancel_rate_limit_unit: "day",
    payment_cancel_rate_limit_window_mode: "rolling",
    payment_alipay_force_qrcode: false,
    payment_alipay_mobile_precreate_deep_link: false,
    table_default_page_size: tablePageSizeDefault,
    table_page_size_options: [10, 20, 50, 100],
    custom_menu_items: [],
    custom_endpoints: [],
    frontend_url: "",
    smtp_host: "",
    smtp_port: 587,
    smtp_username: "",
    smtp_password: "",
    smtp_password_configured: false,
    smtp_from_email: "",
    smtp_from_name: "",
    smtp_use_tls: true,
    turnstile_enabled: false,
    turnstile_site_key: "",
    turnstile_secret_key: "",
    turnstile_secret_key_configured: false,
    recaptcha_enabled: false,
    recaptcha_site_key: "",
    recaptcha_secret_key: "",
    recaptcha_secret_key_configured: false,
    cap_enabled: false,
    cap_api_endpoint: "",
    cap_secret_key: "",
    cap_secret_key_configured: false,
    tencent_captcha_enabled: false,
    tencent_captcha_app_id: "",
    tencent_captcha_app_secret_key: "",
    tencent_captcha_app_secret_key_configured: false,
    tencent_captcha_cloud_secret_id: "",
    tencent_captcha_cloud_secret_id_configured: false,
    tencent_captcha_cloud_secret_key: "",
    tencent_captcha_cloud_secret_key_configured: false,
    tencent_captcha_region: "cn",
    aliyun_captcha_enabled: false,
    aliyun_captcha_access_key_id: "",
    aliyun_captcha_access_key_secret: "",
    aliyun_captcha_access_key_secret_configured: false,
    aliyun_captcha_scene_id: "",
    aliyun_captcha_prefix: "",
    aliyun_captcha_region: "cn",
    local_captcha_enabled: false,
    api_key_acl_trust_forwarded_ip: true,
    client_ip_resolution_mode: "auto_compat",
    client_ip_trusted_proxies: [],
    client_ip_resolution_status: {
      mode: "auto_compat",
      custom_prefix_count: 0,
      static_prefix_count: 0,
      cloudflare_prefix_count: 0,
      cloudflare_ranges_source: "embedded",
      cloudflare_last_success_at: null,
    },
    linuxdo_connect_enabled: false,
    linuxdo_connect_client_id: "",
    linuxdo_connect_client_secret: "",
    linuxdo_connect_client_secret_configured: false,
    linuxdo_connect_redirect_url: "",
    dingtalk_connect_enabled: false,
    dingtalk_connect_client_id: "",
    dingtalk_connect_client_secret: "",
    dingtalk_connect_client_secret_configured: false,
    dingtalk_connect_redirect_url: "",
    dingtalk_connect_corp_restriction_policy: "none",
    dingtalk_connect_internal_corp_id: "",
    dingtalk_connect_bypass_registration: false,
    dingtalk_connect_sync_corp_email: false,
    dingtalk_connect_sync_display_name: false,
    dingtalk_connect_sync_dept: false,
    dingtalk_connect_sync_corp_email_attr_key: "dingtalk_email",
    dingtalk_connect_sync_display_name_attr_key: "dingtalk_name",
    dingtalk_connect_sync_dept_attr_key: "dingtalk_department",
    dingtalk_connect_sync_corp_email_attr_name: localText(
      "钉钉企业邮箱",
      "DingTalk Corporate Email",
    ),
    dingtalk_connect_sync_display_name_attr_name: localText(
      "钉钉姓名",
      "DingTalk Name",
    ),
    dingtalk_connect_sync_dept_attr_name: localText(
      "钉钉部门",
      "DingTalk Department",
    ),
    wechat_connect_enabled: false,
    wechat_connect_app_id: "",
    wechat_connect_app_secret: "",
    wechat_connect_app_secret_configured: false,
    wechat_connect_open_app_id: "",
    wechat_connect_open_app_secret: "",
    wechat_connect_open_app_secret_configured: false,
    wechat_connect_mp_app_id: "",
    wechat_connect_mp_app_secret: "",
    wechat_connect_mp_app_secret_configured: false,
    wechat_connect_mobile_app_id: "",
    wechat_connect_mobile_app_secret: "",
    wechat_connect_mobile_app_secret_configured: false,
    wechat_connect_open_enabled: false,
    wechat_connect_mp_enabled: false,
    wechat_connect_mobile_enabled: false,
    wechat_connect_mode: "open",
    wechat_connect_scopes: "snsapi_login",
    wechat_connect_redirect_url: "",
    wechat_connect_frontend_redirect_url: "/auth/wechat/callback",
    oidc_connect_enabled: false,
    oidc_connect_provider_name: "OIDC",
    oidc_connect_client_id: "",
    oidc_connect_client_secret: "",
    oidc_connect_client_secret_configured: false,
    oidc_connect_issuer_url: "",
    oidc_connect_discovery_url: "",
    oidc_connect_authorize_url: "",
    oidc_connect_token_url: "",
    oidc_connect_userinfo_url: "",
    oidc_connect_jwks_url: "",
    oidc_connect_scopes: "openid email profile",
    oidc_connect_redirect_url: "",
    oidc_connect_frontend_redirect_url: "/auth/oidc/callback",
    oidc_connect_token_auth_method: "client_secret_post",
    oidc_connect_use_pkce: false,
    oidc_connect_validate_id_token: false,
    oidc_connect_allowed_signing_algs: "RS256,ES256,PS256",
    oidc_connect_clock_skew_seconds: 120,
    oidc_connect_require_email_verified: false,
    oidc_connect_userinfo_email_path: "",
    oidc_connect_userinfo_id_path: "",
    oidc_connect_userinfo_username_path: "",
    github_oauth_enabled: false,
    github_oauth_client_id: "",
    github_oauth_client_secret: "",
    github_oauth_client_secret_configured: false,
    github_oauth_redirect_url: "",
    github_oauth_frontend_redirect_url: "/auth/oauth/callback",
    google_oauth_enabled: false,
    google_oauth_client_id: "",
    google_oauth_client_secret: "",
    google_oauth_client_secret_configured: false,
    google_oauth_redirect_url: "",
    google_oauth_frontend_redirect_url: "/auth/oauth/callback",
    enable_model_fallback: false,
    fallback_model_anthropic: "claude-3-5-sonnet-20241022",
    fallback_model_openai: "gpt-4o",
    fallback_model_gemini: "gemini-2.5-pro",
    fallback_model_antigravity: "gemini-2.5-pro",
    enable_identity_patch: true,
    identity_patch_prompt: "",
    ops_monitoring_enabled: true,
    ops_realtime_monitoring_enabled: true,
    ops_query_mode_default: "auto",
    ops_metrics_interval_seconds: 60,
    min_claude_code_version: "",
    max_claude_code_version: "",
    allow_ungrouped_key_scheduling: false,
    openai_low_upstream_rate_priority_enabled: false,
    openai_oauth_scheduling_rate_multiplier: 1,
    openai_content_session_burst_balance_enabled: false,
    scheduler_v2_enabled: false,
    scheduler_v2_status: "disabled",
    scheduler_v2_error: "",
    scheduler_v2_candidate_limit: 64,
    scheduler_v2_scan_limit: 256,
    request_priority_admission_enabled: false,
    request_priority_pending_limit_per_instance: 256,
    request_priority_pending_mib_per_instance: 256,
    openai_advanced_scheduler_enabled: false,
    openai_advanced_scheduler_sticky_weighted_enabled: false,
    openai_advanced_scheduler_subscription_priority_enabled: false,
    openai_advanced_scheduler_lb_top_k: "",
    openai_advanced_scheduler_weight_priority: "",
    openai_advanced_scheduler_weight_load: "",
    openai_advanced_scheduler_weight_queue: "",
    openai_advanced_scheduler_weight_error_rate: "",
    openai_advanced_scheduler_weight_ttft: "",
    openai_advanced_scheduler_weight_reset: "",
    openai_advanced_scheduler_weight_quota_headroom: "",
    openai_advanced_scheduler_weight_upstream_cost: "",
    openai_advanced_scheduler_weight_previous_response: "",
    openai_advanced_scheduler_weight_session_sticky: "",
    stream_mode_performance_enabled: false,
    openai_ws_mode_router_v2_enabled: false,
    openai_visible_output_ttft_enabled: true,
    enable_fingerprint_unification: true,
    enable_metadata_passthrough: false,
    enable_cch_signing: false,
    enable_claude_oauth_system_prompt_injection: true,
    claude_oauth_system_prompt: "",
    claude_oauth_system_prompt_blocks: defaultClaudeOAuthSystemPromptBlocks,
    enable_anthropic_cache_ttl_1h_injection: false,
    rewrite_message_cache_control: false,
    enable_client_dateline_normalization: true,
    antigravity_user_agent_version: "",
    openai_codex_user_agent: "",
    openai_codex_client_version: "",
    openai_codex_client_version_synced: "",
    openai_codex_version_auto_sync_enabled: true,
    min_codex_version: "",
    max_codex_version: "",
    codex_cli_only_blacklist: "",
    codex_cli_only_whitelist: "",
    codex_cli_only_allow_app_server_clients: false,
    codex_cli_only_engine_fingerprint_signals: "",
    balance_low_notify_enabled: false,
    balance_low_notify_threshold: 0,
    balance_low_notify_recharge_url: "",
    subscription_expiry_notify_enabled: true,
    account_quota_notify_enabled: false,
    account_quota_notify_emails: [] as NotifyEmailEntry[],
    channel_monitor_enabled: true,
    channel_monitor_default_interval_seconds: 60,
    channel_monitor_latency_unit: "ms",
    channel_monitor_public_share_enabled: false,
    channel_monitor_public_share_require_auth: false,
    available_channels_enabled: false,
    support_chat_enabled: false,
    support_chat_retention_days: 0,
    model_plaza_enabled: false,
    model_plaza_require_auth: false,
    model_plaza_auto_public_models: false,
    model_plaza_description: "",
    media_studio_enabled: false,
    ipv6_egress_ui_enabled: false,
    affiliate_enabled: false,
    allow_user_view_error_requests: false,
    allow_user_view_usage_details: false,
    custom_model_config_enabled: false,
  };
}
